In [32]:
import numpy as np
arr=np.array([[1,2,3,],[4,5,6]])
print("element at (0,1):",arr[0,1])
print("second row:",arr[1])
print(arr)

element at (0,1): 2
second row: [4 5 6]
[[1 2 3]
 [4 5 6]]


In [33]:
a=np.array([5,10,15])
b=np.array([1,2,3])
result=a+b
print("sum:",result)

sum: [ 6 12 18]


In [34]:
import numpy as np
rand_array=np.random.randint(1,100,size=10)
print("random array:",rand_array)
print("maximum:",np.max(rand_array))
print("minimum:",np.min(rand_array))

random array: [76 53 45 90 77 57 24 73 56 35]
maximum: 90
minimum: 24


In [35]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
reshaped=arr.reshape(2,3)
print("reshaped(2*3):\n",reshaped)
flattened=reshaped.flatten()
print("flattened:",flattened)

reshaped(2*3):
 [[1 2 3]
 [4 5 6]]
flattened: [1 2 3 4 5 6]


In [36]:
import numpy as np
arr=np.array([10,20,30,40,50])
filtered=arr[arr>25]
print("elements>25:",filtered)

elements>25: [30 40 50]


In [37]:
import numpy as np
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
result=np.dot(A,B)
print("matrix A:\n",A)
print("matrix B:\n",B)
print("A*B:\n",result)

matrix A:
 [[1 2]
 [3 4]]
matrix B:
 [[5 6]
 [7 8]]
A*B:
 [[19 22]
 [43 50]]


In [38]:
data=np.array([1,2,3,4,5,6])
print("mean:",np.mean(data))
print("median:",np.median(data))
print("standard deviation:",np.std(data))

mean: 3.5
median: 3.5
standard deviation: 1.707825127659933


In [39]:
import numpy as np

a = np.arange(0, 10)
b = np.linspace(0, 2 * np.pi, 10)

print("arange:", a)
print("linspace:", b)


arange: [0 1 2 3 4 5 6 7 8 9]
linspace: [0.         0.6981317  1.3962634  2.0943951  2.7925268  3.4906585
 4.1887902  4.88692191 5.58505361 6.28318531]


In [40]:
import numpy as np

matrix=np.array([[1,2,3],[4,5,6]])

transpose=matrix.T

print("original:\n",matrix)
print("Transposed:\n",transpose)

original:
 [[1 2 3]
 [4 5 6]]
Transposed:
 [[1 4]
 [2 5]
 [3 6]]


In [41]:
import numpy as np
x=np.array([0,np.pi/2,np.pi])
y=np.sin(x)
print("x values:",x)
print("sin(x):",y)

x values: [0.         1.57079633 3.14159265]
sin(x): [0.0000000e+00 1.0000000e+00 1.2246468e-16]


In [42]:
import pandas as pd

data = {
    'name': ['Alice', 'bob', 'charlie'],
    'age': [25, 30, 22],
    'score': [85, 90, 95]
}
df = pd.DataFrame(data)
print(df)



      name  age  score
0    Alice   25     85
1      bob   30     90
2  charlie   22     95


In [43]:
import numpy as np
import pandas as pd

df = pd.read_csv("students.csv")

print(df.head())
print(df.info())
print(df.describe())


FileNotFoundError: [Errno 2] No such file or directory: 'students.csv'

In [ ]:
import pandas as pd

data = {
    'name': ['Alice', 'bob', 'charlie'],
    'age': [25, 30, 22]
}
df=pd.DataFrame(data)
filtered_df=df[df['age']>25]
print(filtered_df)

In [ ]:
import pandas as pd

data = {
    'Department': ['cs', 'cs', 'it', 'IT'],
    'marks': [25, 30, 22, 89]
}
df = pd.DataFrame(data)
grouped = df.groupby('Department').mean()
print(grouped)


In [ ]:
import pandas as pd

data = {
    'Maths': [90, 56, 79, 98],
    'Science': [25, 30, 22, 89]
}
df = pd.DataFrame(data)
df['average'] = (df['Maths'] + df['Science']) / 2
print(df)
df.to_csv("average.csv", index=False)


In [ ]:
import matplotlib.pyplot as plt
x=[1,2,3,4,5]
y=[10,20,30,40,50]

plt.plot(x,y)
plt.title("simple line graph")
plt.xlabel("x value")
plt.ylabel("y value")
plt.show()

In [ ]:
import matplotlib.pyplot as plt
student=['farhan','junaid','sami','hafeez']
scores=[40,20,30,35]

plt.bar(student,scores,color='skyblue')
plt.title("student scores")
plt.xlabel("student")
plt.ylabel("marks")
plt.show()


In [ ]:
import matplotlib.pyplot as plt
labels=['python','java','c++','c']
sizes=[40,20,30,40]
plt.pie(sizes,labels=labels,autopct='%1.1f%%',startangle=140)
plt.title("programming languages")
plt.axis('equal')
plt.show()

In [ ]:
import matplotlib.pyplot as plt

ages=[18,29,32,34,56,77,23,12,35]
plt.hist(ages,bins=5,color='green')
plt.title("age Distribution")
plt.xlabel("age")
plt.ylabel("frequency")
plt.show()

In [ ]:
import matplotlib.pyplot as plt
x=[1,2,3,4,5]
y=[5,7,8,9,6]
plt.scatter(x,y,color='VIOLET')
plt.title("scatter plot")
plt.xlabel("x value")
plt.ylabel("y value")
plt.show()


In [ ]:
import pandas as pd
ds1 = pd.Series([2, 4, 8, 10])
ds2 = pd.Series([1, 3, 7, 9])
print("Multiply two Series:")
ds = ds1 * ds2
print(ds)
print("Divide Series1 by Series2:")
ds = ds1 / ds2
print(ds)

In [ ]:
import pandas as pd
d1 = {'a': 100, 'b': 200, 'c':300}
print("Original dictionary:")
print(d1)
new_series = pd.Series(d1)
print("Converted series:")
print(new_series)

In [ ]:
import pandas as pd
s = pd.Series([400, 300.12,100, 200])
print("Original Data Series:")
print(s)
new_s = pd.Series(s).sort_values()
print(new_s)

In [ ]:
import pandas as pd
s = pd.Series(data = [1,2,3], index = ['A', 'B', 'C'])
print("Original Data Series:")
print(s)
s = s.reindex(index = ['B','A','C'])
print("Data Series after changing the order of index:")
print(s)


In [ ]:
import pandas as pd
import numpy as np
sr1 = pd.Series([1, 2, 3])
sr2 = pd.Series([2, 3, 6])
print("Original Series:")
print("sr1:")
print(sr1)
print("sr2:")
print(sr2)
print("\nItems of a given series not present in another given series:")
sr11 = pd.Series(np.union1d(sr1, sr2))
sr22 = pd.Series(np.intersect1d(sr1, sr2))
result = sr11[~sr11.isin(sr22)]
print(result)

In [ ]:
import pandas as pd
import numpy as np
exam_data = {'name': ['Manish', 'Dhiraj'],
'score': [12.5, 9]}
labels = ['NAME', 'SCORE']
df = pd.DataFrame(exam_data , index=labels)
print(df)

In [ ]:
import pandas as pd
import numpy as np
exam_data = {'name': ['Manish', 'Dhiraj','Man', 'Dhir'],
'score': [12.5, 91,2.5, 9]}
df = pd.DataFrame(exam_data )
print("First three rows of the data frame:")
print(df.iloc[:3])

In [ ]:
import pandas as pd
import numpy as np
exam_data={'name':['manish','dhiraj','Man', 'Dhir'],
'score': [12.5, 91,2.5, 9]}
df = pd.DataFrame(exam_data )
total_rows=len(df.axes[0])
total_cols=len(df.axes[1])
print("number of rows:"+str(total_rows))
print("number of columns:"+str(total_rows))

In [ ]:
import pandas as pd
import numpy as np
exam_data={'name':['manish','dhiraj','Man', 'Dhir'],
'score': [12.5, 91,2.5, 9]}
df = pd.DataFrame(exam_data )
print("rows where score betwween 15 and 20 (inclusive):")
print(df[df['score'].between(15,20)])

In [ ]:
import pandas as pd
import numpy as np
exam_data = {'name': ['manish', 'dhiraj', 'Man', 'Dhir'],
'score': [12.5, 91, 2.5, 9]}
df = pd.DataFrame(exam_data)
result_sort = df.sort_values(by=['name', 'score'], ascending=[False, True])
print("Sort the DataFrame first by 'name' in descending order, then by 'score' in ascending order:")
print(result_sort)


In [ ]:
from os import replace
import pandas as pd
import numpy as np
exam_data = {'name': ['manish', 'dhiraj', 'Man', 'Dhir'],
'score': [12.5, 91, 20.5, 9]}
df = pd.DataFrame(exam_data)
df['name']=df['name'].replace('manish','anish')
print(df)

In [ ]:
import pandas as pd
import numpy as np
exam_data = {'name': ['manish', 'dhiraj', 'Man', 'Dhir'],
'score': [12.5, 91, 2.5, 9]}
df = pd.DataFrame(exam_data)
medium=['english','hindi','hindi','english']
df['medium']=medium
print("\n new dataframe after inserting the 'medium' column")
print(df)

In [ ]:
import pandas as pd
import numpy as np
exam_data = {'name': ['manish', 'dhiraj', 'Man', 'Dhir'],
'score': [12.5, 91, 2.5, 9]}
df = pd.DataFrame(exam_data)
df=df.rename(columns={'name':'NAME','score':'SCORE'})
print("new dataframe after renaming columns:")
print(df)

In [ ]:
import pandas as pd
import numpy as np
exam_data = {'name': ['manish', 'dhiraj', 'Man', 'Dhir'],
'score': [12.5, 91, 2.5, 9]}
df = pd.DataFrame(exam_data)
df=df[df.score>=20]
print("new dataframe")
print(df)

In [ ]:
import pandas as pd
import numpy as np
s1 = pd.Series(['100', '200', '400'])
s2 = pd.Series(['10', '20', '40'])
print("Data Series:")
print(s1)
print(s2)
df = pd.concat([s1, s2], axis=1)
print("New DataFrame combining two series:")
print(df)

In [ ]:
import pandas as pd
import numpy as np
s1 = pd.Series(['100', '200', '400'])
s2 = pd.Series(['10', '20', '40'])
df = pd.concat([s1, s2], axis=1)
print("Value of Row4")
print(df.iloc[2])

In [ ]:
import pandas as pd
import numpy as np
s1 = pd.Series(['100', '200', '400'])
s2 = pd.Series(['10', '20', '40'])
df = pd.concat([s1, s2], axis=1)
new_col = [1, 2, 3]
idx = 0
df.insert(loc=idx, column='1', value=new_col)
print("\nNew DataFrame")
print(df)

In [ ]:
square=lambda x:x**2
print(square(4))

In [ ]:
numbers = [1, 2, 3, 4, 5, 6]
even_numbers = list(filter(lambda x: (x % 2 == 0), numbers))
print(even_numbers)


In [ ]:
data=[(1,'apple'),(3,'banana'),(2,'cherry')]
sorted_data=sorted(data,key=lambda x:x[1])
print(sorted_data)

In [ ]:
multiply = lambda x, y, z: x * y * z
print(multiply(2, 3, 4))


In [ ]:
numbers=[1,2,3,4,5]
doubled=list(map(lambda x:x*2,numbers))
print(doubled)

In [ ]:
students=[{"name": "alice", "score": 85},
          {"name": "bob", "score": 92},
          {"name": "charli", "score": 78}]
sorted_students=sorted(students,key=lambda student:student['score'])
print(sorted_students)

In [ ]:
check_even_odd = lambda num: "Even" if num % 2 == 0 else "Odd"
print(check_even_odd(4))
print(check_even_odd(7))


In [ ]:
s1='Geeks for Geeks'
s2=lambda func:func.upper()
print(s2(s1))

In [ ]:
n=lambda x:"positive" if x>0 else "negative" if x<0 else "zero"
print(n(5))
print(n(-3))
print(n(0))

In [ ]:
li=[lambda arg=x:arg*10 for x in range(1,5)]
for i in li:
  print(i())

In [ ]:
check=lambda x:"even" if x % 2==0 else"odd"
print(check(4))
print(check(7))

In [ ]:
calc=lambda x,y:(x+y,x-y)
res=calc(3,4)
print(res)

In [ ]:
n=[1,2,3,4,5,6]
even=filter(lambda x:x%2==0,n)
print(list(even))

In [ ]:
a=[1,2,3,4,]
b=map(lambda x:x*2,a)
print(list(b))

In [ ]:
from functools import reduce
a=[1,2,3,4]
b=reduce(lambda x,y:x*y,a)
print(b)


In [ ]:
number=list(range(1,21))
filtered=list(filter(lambda x:x%2==0 and x%3==0,number))
print(filtered)

In [ ]:
sentence = "lambda functions are powerful"
sentence_split = sentence.split()
reversed_words = list(map(lambda word: word[::-1], sentence_split))
print(" ".join(reversed_words))


In [ ]:
people=["alicjohnson","bolsmith","charlie brown"]
sorted_by_last=sorted(people,key=lambda name:name.split()[-1])
print(sorted_by_last)

In [ ]:
operations = {
    'add': lambda x, y: x + y,
    'sub': lambda x, y: x - y,
    'mul': lambda x, y: x * y,
    'div': lambda x, y: x / y if y != 0 else 'Error'
}

print(operations['add'](10, 5))
print(operations['div'](10, 0))


In [ ]:
numbers = list(range(1, 21))
# Get numbers that are divisible by both 2 and 3
filtered = list(filter(lambda x: x % 2 == 0 and x % 3 == 0, numbers))
print(filtered)


In [ ]:
check_even_odd = lambda num: "Even" if num % 2 == 0 else "Odd"
print(check_even_odd(4))
print(check_even_odd(7))


In [ ]:
s1 = 'GeeksforGeeks'

s2 = lambda func: func.upper()
print(s2(s1))


In [ ]:
n = lambda x: "Positive" if x > 0 else "Negative" if x < 0 else "Zero"

print(n(5))
print(n(-3))
print(n(0))


In [ ]:
li = [lambda arg=x: arg * 10 for x in range(1, 5)]
for i in li:
    print(i())


In [ ]:
check = lambda x: "Even" if x % 2 == 0 else "Odd"

print(check(4))
print(check(7))



In [ ]:
calc = lambda x, y: (x + y, x * y)

res = calc(3, 4)
print(res)


In [ ]:
n = [1, 2, 3, 4, 5, 6]
even = filter(lambda x: x % 2 == 0, n)
print(list(even))


In [ ]:
a = [1, 2, 3, 4]
b = map(lambda x: x * 2, a)
print(list(b))


In [ ]:
from functools import reduce

a = [1, 2, 3, 4]
b = reduce(lambda x, y: x * y, a)
print(b)



In [ ]:
#1
import pandas as pd
ds1 = pd.Series([2, 4, 8, 10])
ds2 = pd.Series([1, 3, 7, 9])
print("Multiply two Series:")
ds = ds1 * ds2
print(ds)
print("Divide Series1 by Series2:")
ds = ds1 / ds2
print(ds)

In [ ]:
#2
import pandas as pd
d1 = {'a': 100, 'b': 200, 'c':300}
print("Original dictionary:")
print(d1)
new_series = pd.Series(d1)
print("Converted series:")
print(new_series)


In [ ]:
#3
import pandas as pd
s = pd.Series([400, 300.12,100, 200])
print("Original Data Series:")
print(s)
new_s = pd.Series(s).sort_values()
print(new_s)


In [ ]:
#4
import pandas as pd
s = pd.Series(data = [1,2,3], index = ['A', 'B', 'C'])
print("Original Data Series:")
print(s)
s = s.reindex(index = ['B','A','C'])
print("Data Series after changing the order of index:")
print(s)


In [ ]:
#5
import pandas as pd
import numpy as np
sr1 = pd.Series([1, 2, 3])
sr2 = pd.Series([2, 3, 6])
print("Original Series:")
print("sr1:")
print(sr1)
print("sr2:")
print(sr2)
print("\nItems of a given series not present in another given series:")
sr11 = pd.Series(np.union1d(sr1, sr2))
sr22 = pd.Series(np.intersect1d(sr1, sr2))
result = sr11[~sr11.isin(sr22)]
print(result)

In [ ]:
#6
import pandas as pd
import numpy as np
exam_data = {'name': ['Manish', 'Dhiraj'],
'score': [12.5, 9]}
labels = ['NAME', 'SCORE']
df = pd.DataFrame(exam_data , index=labels)
print(df)


In [ ]:
#7
import pandas as pd
import numpy as np
exam_data = {'name': ['Manish', 'Dhiraj','Man', 'Dhir'],
'score': [12.5, 91,2.5, 9]}
df = pd.DataFrame(exam_data )
print("First three rows of the data frame:")
print(df.iloc[:3]) #print(df.head(3))

In [ ]:
#8
import pandas as pd
import numpy as np
exam_data = {'name': ['Manish', 'Dhiraj','Man', 'Dhir'],
'score': [12.5, 91,2.5, 9]}
df = pd.DataFrame(exam_data )
total_rows=len(df.axes[0])
total_cols=len(df.axes[1])
print("Number of Rows: "+str(total_rows))
print("Number of Columns: "+str(total_cols))


In [ ]:
#9
import pandas as pd
import numpy as np
exam_data = {'name': ['Manish', 'Dhiraj','Man', 'Dhir'],
'score': [12.5, 91,20.5, 19]}
df = pd.DataFrame(exam_data )
print("Rows where score between 15 and 20 (inclusive):")
print(df[df['score'].between(15, 20)])


In [ ]:
#10
import pandas as pd
import numpy as np
exam_data = {'name': ['Manish', 'Dhiraj','Man', 'Dhir'],
'score': [12.5, 91,20.5, 19]}
df = pd.DataFrame(exam_data )
result_sort=df.sort_values(by=['name', 'score'], ascending=[True,False])
print("Sort the data frame first by ‘name’ in descending order, then by ‘score’ in ascending order:")
print(result_sort)

In [ ]:
import pandas as pd
data={ 'name':['rupa','sita','suresh'],
      'age':[24,45,70],
       'city':['bgk','kkr','kkg']}
df=pd.DataFrame(data)
df=df['age'].mean()
print(df)

In [ ]:
#11
import pandas as pd
import numpy as np
exam_data = {'name': ['Manish', 'Dhiraj','Man', 'Dhir'],
'score': [12.5, 91,20.5, 19]}
df = pd.DataFrame(exam_data )
df['name'] = df['name'].replace('Manish', 'Anish')
print(df)


In [ ]:
#12
import pandas as pd
import numpy as np
exam_data = {'name': ['Manish', 'Dhiraj','Man', 'Dhir'],
'score': [12.5, 91,20.5, 19]}
df = pd.DataFrame(exam_data )
medium = ['english','hindi','hindi','english']
df['medium'] = medium
print("\nNew DataFrame after inserting the 'medium' column")
print(df)


In [ ]:
#13
import pandas as pd

exam_data = {'name': ['Manish', 'Dhiraj','Man', 'Dhir'],
'score': [12.5, 91,20.5, 19]}
df = pd.DataFrame(exam_data )
df = df.rename(columns={'name': 'NAME', 'score': 'SCORE'})
print("New DataFrame after renaming columns:")
print(df)

In [ ]:
#14
import pandas as pd
import numpy as np
exam_data = {'name': ['Manish', 'Dhiraj','Man', 'Dhir'],
'score': [12.5, 91,20.5, 19]}
df = pd.DataFrame(exam_data )
df = df[df.score >= 20]
print("New DataFrame")
print(df)

In [ ]:
#15
import pandas as pd
import numpy as np
s1 = pd.Series(['100', '200', '400'])
s2 = pd.Series(['10', '20', '40'])
print("Data Series:")
print(s1)
print(s2)
df = pd.concat([s1, s2], axis=1)
print("New DataFrame combining two series:")
print(df)

In [ ]:
#16th program
import pandas as pd
import numpy as np
s1 = pd.Series(['100', '200', '400'])
s2 = pd.Series(['10', '20', '40'])
df = pd.concat([s1, s2], axis=1)
print("Value of Row4")
print(df.iloc[2])


In [ ]:
# DATA HANDLING


#17th program
import pandas as pd
import numpy as np
s1 = pd.Series(['100', '200', '400'])
s2 = pd.Series(['10', '20', '40'])
df = pd.concat([s1, s2], axis=1)
new_col = [1, 2, 3]
# insert the said column at the beginning in the DataFrame
idx = 0
df.insert(loc=idx, column='1', value=new_col)
print("\nNew DataFrame")
print(df)

In [ ]:
import pandas as pd
S1=pd.Series([10,20,30,40])
S2=pd.Series([1.5,2.5,3.5], index =['a','b','c'])
S3=pd.Series({'maths':85,'science': 90,'english':72})
print(S1[0])
print(S2['b'])
print(S1[1:3])
print(S1+10)
print(S1+2)
print(S1[S1>20])
S4=pd.Series([100,200,300],index=['a','b','c'])
print(S2+S4)
print(S1.mean())

In [ ]:
import pandas as pd
data ={'Name':['Rupa','Sita','Geeta'],
       'Age':[25,30,35],
       'City':['Bagalkot','Solapur','Gulbarga']}
df=pd.DataFrame(data)
Salary=[50000,60000,70000]
df['Salary']=Salary
print("After addig a new coloumn of salary")
print(df)

In [ ]:
import pandas as pd
data ={'Name':['Rupa','Sita','Geeta'],
       'Age':[25,30,35],
       'City':['Bagalkot','Solapur','Gulbarga']}
df=pd.DataFrame(data)
result_sort=df.sort_values(by=['Age'],ascending=[True])
print("it sorts the dataframe of Age in Ascending order")
print(df)

In [ ]:
import pandas as pd

# 1. 	Create a Pandas Series of 5 elements: [5, 10, 15, 20, 25]
s1 = pd.Series([5, 10, 15, 20, 25])
print("Series s1:")
print(s1)

# 2. Assign custom index ['a', 'b', 'c', 'd', 'e'] to the above Series.
s1.index = ['a', 'b', 'c', 'd', 'e']
print("\n2. Series with custom index:")
print(s1)

# 3 Access the element at index 'c'.
print("\n3. Element at index 'c':", s1['c'])

# 4.	Find the maximum value in the Series.
print("\n4. Maximum value in s1:", s1.max())

# 5.	Add 5 to each element of the Series.
print("\n5. Series after adding 5 to each element:")
print(s1 + 5)

# 6.	Create a Series using a dictionary: {'apple': 50, 'banana': 30, 'cherry': 20}
prices = pd.Series({'apple': 50, 'banana': 30, 'cherry': 20})
print("\n6. Price Series:")
print(prices)

# 7. Filter the Series to show only fruits with price > 25.
print("\n7. Fruits with price > 25:")
print(prices[prices > 25])

#8.	Multiply all prices by 1.2 (simulate a 20% price increase).
print("\n8. Prices after 20% increase:")
print(prices * 1.2)

# 9.Add another Series {'banana': 10, 'cherry': 5, 'date': 15} to the above and explain the result.
new_prices = pd.Series({'banana': 10, 'cherry': 5, 'date': 15})
total_prices = prices + new_prices
print("\n9. Total prices after adding new_prices:")
print(total_prices)
print("Explanation: Values are added by matching keys. If a key is missing in one, result is None.")

# 10.	Find the mean and standard deviation of a Series of numbers.
marks = pd.Series([70, 85, 90, 65, 88])
print("\n10. Mean of marks:", marks.mean())
print("Std deviation of marks:", marks.std())

# 11.	Two Series contain student marks in two subjects. How do you compute the total marks for each student?
sub1 = pd.Series({'Yash': 85, 'Alok': 78, 'Charlie': 92})
sub2 = pd.Series({'Yash': 88, 'Alok': 89, 'Charlie': 90})
total_marks = sub1 + sub2
print("\n11. Total marks for each student:")
print(total_marks)

# 12.	You have a Series of timestamps. How can you extract only the months?
dates = pd.Series(pd.to_datetime(['2025-04-22', '2025-07-10']))
months = dates.dt.month
print("\n12. Months extracted from timestamps:")
print(months)

# 13.	Find the index of the maximum value in a Series.
print("\n13. Index of max value in s1:", s1.idxmax())

Series s1:
0     5
1    10
2    15
3    20
4    25
dtype: int64

2. Series with custom index:
a     5
b    10
c    15
d    20
e    25
dtype: int64

3. Element at index 'c': 15

4. Maximum value in s1: 25

5. Series after adding 5 to each element:
a    10
b    15
c    20
d    25
e    30
dtype: int64

6. Price Series:
apple     50
banana    30
cherry    20
dtype: int64

7. Fruits with price > 25:
apple     50
banana    30
dtype: int64

8. Prices after 20% increase:
apple     60.0
banana    36.0
cherry    24.0
dtype: float64

9. Total prices after adding new_prices:
apple      NaN
banana    40.0
cherry    25.0
date       NaN
dtype: float64
Explanation: Values are added by matching keys. If a key is missing in one, result is None.

10. Mean of marks: 79.6
Std deviation of marks: 11.326958991715296

11. Total marks for each student:
Yash       173
Alok       167
Charlie    182
dtype: int64

12. Months extracted from timestamps:
0    4
1    7
dtype: int32

13. Index of max value in s1: e


In [ ]:
# Array aggregation functions
import numpy as np
arr=np.array([1,2,3,4])
print(arr.sum())
print(arr.mean())
print(arr.min())
print(arr.max())
print(arr.std())

10
2.5
1
4
1.118033988749895


In [ ]:
import numpy as np
array=np.random.randint(16,size=(2,2))
print("Input Array:\n",array)
print("largest number in x axis:",np.max(array,axis =1))
print("largest number in y axis :",np.max(array,axis=0))

Input Array:
 [[10  5]
 [10 13]]
largest number in x axis: [10 13]
largest number in y axis : [10 13]


In [ ]:
import numpy as np
import random
array=np.random.randint(16,size=(2,2))
print("Input array:\n",array)
print("smallest  number in x axis:",np.min(array,axis=1))
print("smallest number in y axis:",np.min(array,axis=0))

Input array:
 [[ 4  4]
 [11 13]]
smallest  number in x axis: [ 4 11]
smallest number in y axis: [4 4]


In [44]:
#Vectorized operations
arr = np.array([1, 2, 3])
print(arr + 2)
print(np.sin(arr))

[3 4 5]
[0.84147098 0.90929743 0.14112001]


In [45]:
#Broadcasting
arr = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])
print(arr + arr2)


[2 4 6]


In [46]:
arr = np.array([1, 2, 3])
squared = list(map(lambda x: x**2, arr))
print("Squared using map:", squared)


Squared using map: [np.int64(1), np.int64(4), np.int64(9)]


In [47]:
def square(number):
  return number*number

nums= [1,2,3,4]
squared_numbers = list(map(square,nums))
print(squared_numbers)


[1, 4, 9, 16]


In [48]:
nums1= [1,2,3,4,5,6]
squareOfnums1 = list(map(lambda n:n*n,nums1))
print(squareOfnums1)


[1, 4, 9, 16, 25, 36]


In [49]:
#filter
def is_even(n):
  if n % 2 ==0:
    return True
  else:
    return False
nums = [1,2,3,4]
evens = list(filter(is_even,nums))
print(evens)


[2, 4]


In [50]:
arr=[3,4,5,6,7]
even = list(filter(lambda x: x % 2 == 0, arr))
print("Even numbers:", even)


Even numbers: [4, 6]


In [51]:
from functools import reduce
def sum_all(a,b):
  return a+b
nums = [1,2,3,4]
sum = reduce(sum_all,nums)
print(sum)


10


In [52]:
from functools import reduce
total = reduce(lambda x, y: x + y, arr)
print("Sum using reduce:", total)


Sum using reduce: 25


In [53]:
# Creating a Series
import pandas as pd

data = pd.Series([10, 20, 30, 40], index=['a', 'b', 'c', 'd'])
print(data)


a    10
b    20
c    30
d    40
dtype: int64


In [54]:
# import pandas as pd
import pandas as pd
lst = ['Apple', 'Mango', 'Banana', 'Pine Apple', 'Grapes', 'Watermelon']
df = pd.DataFrame(lst)
print(df)


            0
0       Apple
1       Mango
2      Banana
3  Pine Apple
4      Grapes
5  Watermelon


In [55]:
import pandas as pd
data = {
    'Department': ['HR', 'HR', 'IT', 'IT', 'Finance', 'Finance'],
    'Employee': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank'],
    'Salary': [50000, 55000, 60000, 65000, 70000, 72000],
    'Age': [25, 30, 28, 32, 40, 38]
}
df = pd.DataFrame(data)
print(df)
#Simple Aggregation
# Mean salary
print(df['Salary'].mean())
# Max age
print(df['Age'].max())

#3Group By a Column
# Group by Department and get mean salary
grouped = df.groupby('Department')['Salary'].mean()
print(grouped)

#Multiple Aggregation Functions
# Get multiple aggregations
grouped = df.groupby('Department')['Salary'].agg(['mean', 'max', 'min'])
print(grouped)

#Group By Multiple Columns
# Add another field to group (if exists)
df['Location'] = ['Mumbai', 'Delhi', 'Mumbai', 'Delhi', 'Mumbai', 'Delhi']
# Group by Department and Location
grouped = df.groupby(['Department', 'Location'])['Salary'].mean()
print(grouped)

#Using agg() with Custom Functions
# Custom aggregation on multiple columns
result = df.groupby('Department').agg({
    'Salary': 'mean',
    'Age': ['min', 'max']
})
print(result)




  Department Employee  Salary  Age
0         HR    Alice   50000   25
1         HR      Bob   55000   30
2         IT  Charlie   60000   28
3         IT    David   65000   32
4    Finance      Eva   70000   40
5    Finance    Frank   72000   38
62000.0
40
Department
Finance    71000.0
HR         52500.0
IT         62500.0
Name: Salary, dtype: float64
               mean    max    min
Department                       
Finance     71000.0  72000  70000
HR          52500.0  55000  50000
IT          62500.0  65000  60000
Department  Location
Finance     Delhi       72000.0
            Mumbai      70000.0
HR          Delhi       55000.0
            Mumbai      50000.0
IT          Delhi       65000.0
            Mumbai      60000.0
Name: Salary, dtype: float64
             Salary Age    
               mean min max
Department                 
Finance     71000.0  38  40
HR          52500.0  25  30
IT          62500.0  28  32


In [56]:
import pandas as pd
d1 = {"Name": ["Pankaj", "Lisa", "David"], "ID": [1, 2, 3], "Role": ["CEO", "Editor", "Author"]}
df = pd.DataFrame(d1)
print(df)
df_melted = pd.melt(df, id_vars=["ID"],
value_vars=["Name", "Role"])
print(df_melted)


     Name  ID    Role
0  Pankaj   1     CEO
1    Lisa   2  Editor
2   David   3  Author
   ID variable   value
0   1     Name  Pankaj
1   2     Name    Lisa
2   3     Name   David
3   1     Role     CEO
4   2     Role  Editor
5   3     Role  Author


In [57]:
import pandas as pd
data = {
    'Date': ['2024-01-01', '2024-01-01', '2024-01-02', '2024-01-02'],
    'City': ['Mumbai', 'Delhi', 'Mumbai', 'Delhi'],
    'Temperature': [33, 28, 34, 27]
}
df = pd.DataFrame(data)
print("Original:\n", df)

pivoted = df.pivot(index='Date', columns='City', values='Temperature')
print("\nPivoted:\n", pivoted)


Original:
          Date    City  Temperature
0  2024-01-01  Mumbai           33
1  2024-01-01   Delhi           28
2  2024-01-02  Mumbai           34
3  2024-01-02   Delhi           27

Pivoted:
 City        Delhi  Mumbai
Date                     
2024-01-01     28      33
2024-01-02     27      34


In [58]:
import pandas as pd

data = {
    'Student': ['Alice', 'Bob', 'Charlie'],
    'Math': [85, 90, 78],
    'Science': [92, 88, 85],
    'English': [75, 80, 72]
}
df = pd.DataFrame(data)
print("Original Wide DataFrame:\n", df)


Original Wide DataFrame:
    Student  Math  Science  English
0    Alice    85       92       75
1      Bob    90       88       80
2  Charlie    78       85       72


In [59]:
melted_df = pd.melt(df,
                    id_vars=['Student'],
                    var_name='Subject',
                    value_name='Marks')
print("\nMelted Long DataFrame:\n", melted_df)



Melted Long DataFrame:
    Student  Subject  Marks
0    Alice     Math     85
1      Bob     Math     90
2  Charlie     Math     78
3    Alice  Science     92
4      Bob  Science     88
5  Charlie  Science     85
6    Alice  English     75
7      Bob  English     80
8  Charlie  English     72


In [ ]:
import pandas as pd
import numpy as np
# Generate date range (10 daily periods starting from Jan 1, 2024)
dates = pd.date_range(start='2024-01-01', periods=10, freq='D')

# Create a time series
ts = pd.Series(np.random.randint(100, 200, size=10), index=dates)
print(ts)



2024-01-01    174
2024-01-02    190
2024-01-03    170
2024-01-04    167
2024-01-05    114
2024-01-06    111
2024-01-07    194
2024-01-08    141
2024-01-09    166
2024-01-10    154
Freq: D, dtype: int32


In [60]:
import pandas as pd
import numpy as np
from functools import reduce

# Sample DataFrame
df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 32, 30, 29],
    'Salary': [50000, 60000, 55000, 52000]
})
print(df)


      Name  Age  Salary
0    Alice   25   50000
1      Bob   32   60000
2  Charlie   30   55000
3    David   29   52000


In [61]:
df['Updated_Salary'] = df['Salary'].apply(lambda x: x * 1.10)

df['Age_Group'] = df['Age'].apply(lambda x: 'Young' if x < 30 else 'Adult')
print(df)


      Name  Age  Salary  Updated_Salary Age_Group
0    Alice   25   50000         55000.0     Young
1      Bob   32   60000         66000.0     Adult
2  Charlie   30   55000         60500.0     Adult
3    David   29   52000         57200.0     Young


In [62]:
# Convert names to uppercase
df['Name_Upper'] = df['Name'].map(lambda x: x.upper())
# Map specific values
salary_levels = {50000: 'Low', 55000: 'Medium', 60000: 'High'}
df['Salary_Level'] = df['Salary'].map(salary_levels)
print(df)


      Name  Age  Salary  Updated_Salary Age_Group Name_Upper Salary_Level
0    Alice   25   50000         55000.0     Young      ALICE          Low
1      Bob   32   60000         66000.0     Adult        BOB         High
2  Charlie   30   55000         60500.0     Adult    CHARLIE       Medium
3    David   29   52000         57200.0     Young      DAVID          NaN


In [63]:
# Get employees with salary > 52000
filtered_df = df[df['Salary'] > 52000]
filtered_df = df[df['Name'].apply(lambda x: x.startswith('A'))]
print(filtered_df)


    Name  Age  Salary  Updated_Salary Age_Group Name_Upper Salary_Level
0  Alice   25   50000         55000.0     Young      ALICE          Low
